### PR TITLE
5829: Fixed the SQL statement in PrimaryResourcesDAO.class.php

### PR DESCRIPTION
**Pull request by cindyli**
To work with the new mysql prepare() function.

### CODE REVIEW

**Comment by cindyli** [comment]
This pull request actually fixes include/classes/DAO/TestsQuestionsDAO.class.php instead of PrimaryResourcesDAO.class.php

**Comment by atutor** [comment]
This seems to be working, thanks. I've applied it to the other cases where IN() is used.

Do you have any thoughts on the dynamic column/value pairs. For example:
https://github.com/atutor/AContent/blob/master/include/classes/DAO/UserGroupsDAO.class.php#L143

**Comment by cindyli** [comment]
It probably can be handled like:
```
$sql = "UPDATE ".TABLE_PREFIX."user_groups 
           SET ? = ?
         WHERE user_group_id = ?";
$values = array($fieldName, $fieldValue, $userGroupID);
$types = "ssi";
return $this->execute($sql, $values, $types);
```
so that `$fieldName` also gets verified.

**Comment by atutor** [comment]
Are you thinking specifying both column and value variables as strings will be safe. In this case I think it would be okay, since values are always strings. There are other cases though when we don't know what type the value is. In all cases I think field names will be strings. Is it okay to call an integer a string, or is mysql going to complain when a string get inserted into an integer field. 

However, according to the docs, it seems fieldnames cannot be prepared.
I did find this, but I'm hoping there's a more elegant solution. 
https://stackoverflow.com/questions/12064118/can-i-dynamically-select-fields-in-a-database-using-parameterised-sql

**Comment by cindyli** [comment]
Good finding, Greg.

I double checked and the PHP documentation does not recommend the use of “?” for table field names. If so, to prevent the SQL injection through field name variables, I agreed with a comment in the stackoverflow thread you found, that is to sanitize field names before building the SQL. The sanitization I think of is to ensure all field names are among the actual field name values of the updated table since once the updated table is known, all field names belonging to that table are known too.

Let me know if you have other ideas. Thanks.

Cindy

**Pull request merged**
